ALTER TABLE users
  ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT 'Unknown',
  ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT 'User';

ALTER TABLE users
  ALTER COLUMN first_name DROP DEFAULT,
  ALTER COLUMN last_name DROP DEFAULT;



